# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: ************

aws:
  access_key_id: ************
  secret_access_key: ************
  bucket: ************

azure:
  api_management:
    subscription_key: ************

auth0:
  domain: ****.**.auth0.com
  app:
    client_id: ******
    client_secret: ************
  m2m:
    client_id: ******
    client_secret: ************

cockroachdb:
  database: **************
  user: **************
  password: **************
  host: **************.cockroachlabs.cloud
  port: *****
  cluster: **************
