secret_key_base: ************

gcp:
  cloud_sql:
    password: ************
    host: /cloudsql/project:region:instance-name

auth0:
  domain: ****.**.auth0.com
  app:
    client_id: ******
    client_secret: ************
  m2m:
    client_id: ******
    client_secret: ************
