secret_key_base: ************

gcp:
  cloud_sql:
    password: ************
    host: /cloudsql/project:region:instance-name

azure:
  api_management:
    subscription_key: ************

auth0:
  domain: ****.**.auth0.com
  app:
    client_id: ******
    client_secret: ************
  m2m:
    client_id: ******
    client_secret: ************
