secret_key_base: ************

azure:
  api_management:
    subscription_key: ************

auth0:
  domain: ****.**.auth0.com
  app:
    client_id: ******
    client_secret: ************
  m2m:
    client_id: ******
    client_secret: ************

cockroachdb:
  database: **************
  user: **************
  password: **************
  host: **************.cockroachlabs.cloud
  port: *****
  cluster: **************
