# Used as the base secret for all MessageVerifiers in Rails, including the one protecting cookies.
secret_key_base: ************

auth0:
  domain: ****.**.auth0.com
  app:
    client_id: ******
    client_secret: ************
  m2m:
    client_id: ******
    client_secret: ************

cloudflare:
  r2:
    account_id: **************
    token: **************
    access_key_id: **************
    secret_access_key: **************
    bucket: **************
